name: Test

on:
  workflow_dispatch:

  pull_request:
    branches:
      - "main"

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
        django: ["4.2", "5.0", "5.1", "5.2"]
        exclude:
          - { python: "3.13", django: "4.2" }
          - { python: "3.13", django: "5.0" }

    name: Tests - python ${{ matrix.python }} × django ${{ matrix.django }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker build -f dev/docker/Dockerfile --build-arg PYTHON_VERSION=${{ matrix.python }} --build-arg DJANGO_VERSION=${{ matrix.django }} -t cotton-test-app dev/example_project

      - name: Start Container
        run: |
          docker compose -f dev/docker/docker-compose.yaml up -d

      - name: Run Tests
        run: docker exec -t cotton-dev-app coverage run manage.py test

      - name: Coverage Report
        run: docker exec -t cotton-dev-app coverage report

      - name: Stop and Remove Services
        run: docker compose -f dev/docker/docker-compose.yaml down
